### ISSUE TITLE
support platform aarch64-unknown-linux-musl

### ISSUE THREAD

**Issue by ahaoboy** [axodotdev/cargo-dist#1207]
https://github.com/axodotdev/cargo-dist/releases

Although cargo-dist itself supports aarch64-unknown-linux-musl, it does not support it by default.

```
Apple Silicon macOS (aarch64-apple-darwin)
Intel macOS (x86_64-apple-darwin)
x64 Linux (x86_64-unknown-linux-gnu)
x64 MUSL Linux (x86_64-unknown-linux-musl)
x64 Windows (x86_64-pc-windows-msvc)
```

```
cargo-dist --version
cargo 0.19.1
```

**Comment by ahaoboy** [comment]
> Apologies for the delay! To clarify what you goal is- when you talk about the "defaults" do you mean the targets that are listed in `cargo dist init`?


Yes, it seems that it is not possible to publish programs for the aarch64-unknown-linux-musl platform at the moment

**Comment by ashleygwilliams** [comment]
ah! @ahaoboy - i think this is a misunderstanding, and hopefully something we can address with documentation. cargo-dist supports any number of targets, we just do not list all possible targets in the `init` dialogue. if you'd like to build for `aarch64-unknown-linux-musl` you can do it the way cargo-dist does it for itself by adding the target to the targets key: https://github.com/axodotdev/cargo-dist/blob/main/Cargo.toml#L88

because Github does not offer a native runner for this target, you'll also need to specify a custom runner for it. axo uses buildjet for runners, but you are welcome to use any github actions compatible runner! https://github.com/axodotdev/cargo-dist/blob/main/Cargo.toml#L106

let me know if this helps!

**Comment by ahaoboy** [comment]
Thx
