### ISSUE TITLE
Error finding symbols for Windows in CI

### ISSUE THREAD

**Issue by oeb25** [axodotdev/cargo-dist#122]
I've been running into issues when running the `release.yml` in CI specifically on Windows.

The log looks something like the following:

```js
    Finished dist [optimized + debuginfo] target(s) in 19m 08s
dist ran successfully
{"error": {"message": "failed to find symbols checko for checko 0.1.4 (path+file:///D:/a/checkr/checkr/checko)","severity": "error","causes": [],"labels": [],"related": []}}
jq: error (at <stdin>:1): Cannot iterate over null (null)
uploading...
requires at least 2 arg(s), only received 1
uploaded!
```

Linux and macOS builds just fine, so it might be that some `.exe` extension got lost somewhere?

I have two CI runs where this failed:
- https://github.com/team-checkr/checkr/actions/runs/4165906899/jobs/7209551911
- https://github.com/team-checkr/checkr/actions/runs/4166205704/jobs/7210238410

My [CI script](https://github.com/team-checkr/checkr/actions/runs/4165906899/workflow) is a little bit modified but nothing too huge. That is, it adds `wasm32-unknown-unknown` target and builds a Node application before starting `cargo-dist`, and is on `nightly`.

If there's anything I can provide in order to debug this, let me know!

**Comment by Gankra** [comment]
This was plenty, thanks! The problem is this line:

https://github.com/team-checkr/checkr/blob/6fe79c4cfa62f79e8e34a1e4185bf4d9d11b0dca/Cargo.toml#L13

As it turns out, "strip" uh... doesn't do what you want, and [cargo's docs explain it poorly](https://doc.rust-lang.org/cargo/reference/profiles.html#strip), making it sound like it's just for making sure the binary is minimized, while [rustc's docs are more clear that this just banishes the debuginfo to hell](https://doc.rust-lang.org/rustc/codegen-options/index.html#strip), and nothing complains that you're both asking for split-debuginfo and no debuginfo, so cargo-dist is lost.

I should really make symbols more of an optional output or something...

**Comment by oeb25** [comment]
Damn, that's interesting!

The reasoning for adding `strip = "debuginfo"` in my case, was that the binaries produced for Linux where around 100MB while they were only around 10MB for macOS and Windows. Running `strip` on my downloaded binary reduced it to the same ballpark of 10MB.

I'm unsure whether this is a `cargo-dist` issue, or more of a _cargo-build-flags-in-general_ problem. Either way I'd love to find a combination of flags to get the binary size down, but I guess that might be related to #118?

As a side note: Would it make sense to run a `cargo dist lint`-like command at the start of the CI pipeline? You know, check for well-known illegal config permutation, such as this. Or would that maybe be more appropriate as a cargo feature alone?

**Comment by Gankra** [comment]
In this case it's hard to detect because you had it in another profile, and in general cargo does not make it easy to ask what the net profile/flags are. (would love to be wrong here)

I need to do an audit of the exact behaviour of these various flags, there's a bunch of weird platform-specific conventions that make them behave non-intuitively.

**Comment by Gankra** [comment]
The next release will have pdb support temporarily disabled pending #136
