### ISSUE TITLE
Request: remove version numbers from GH release asset names

### ISSUE THREAD

**Issue by milesj** [axodotdev/cargo-dist#184]
I'm using cargo-dist for my project proto: https://github.com/moonrepo/proto/releases

It works well, but one think that's quite annoying is that all the asset names include the version number. This means we can no longer use the "latest" shortcut on GitHub. For example, this is no longer possible:

https://github.com/moonrepo/proto/releases/latest/download/proto_cli-installer.sh

Instead we need a fully qualified URL:

https://github.com/moonrepo/proto/releases/download/proto_cli-v0.1.5/proto_cli-v0.1.5-installer.sh 

This will require us to constantly update our docs to point to the latest version, or setup some kind of HTTP proxy that redirects to the latest version.

**Comment by Gankra** [comment]
Yes we should do this, notes for why we didn't and why I have changed mind:

* it's nice-to-have the version name in there so that anyone who downloads multiple versions doesn't end up with `installer.sh (1)` `installer.sh (2)`... 
* i thought github didn't support "latest download urls" because I foolishly assumed the schema would be uniform and got a 404. the above comment uses the correct schema, demonstrating i'm incorrect. 
   *  `.../releases/latest/download/...` 
   * `.../releases/download/<tag>/...`
