### ISSUE TITLE
Support globs for files to "include"

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [axodotdev/cargo-dist#193]
I have a directory structure in my source tree containing multiple definition files (.toml) and docs files (.md) at various levels.

I would like to include these files in the distrbuted packages, using the original folder structure.

Selecting them with a glob would be ergonomic, and not have them all flattened into the tarball root folder.

**Comment by vstojkovic** [comment]
I would also love to see this feature. A project I'm working on depends on the `steamworks` crate which bundles a redistributable DLL with it. I'm already using `cargo-dist` to cut my releases, and I would like to be able to tell it to grab that DLL from the built `steamworks-sys` crate rather than include it in my repo and keep it in sync with the crate I depend on.

**Comment by Gankra** [comment]
As of 0.1.0 you can `include = ["path/to/some/dir"]` and it *should* preserve the whole structure/name of "dir" (bug if not). 

I've filed another issue for the second comment: https://github.com/axodotdev/cargo-dist/issues/383
