### ISSUE TITLE
all items in release table say "tarball", even for zip files

### ISSUE THREAD

**Issue by zkat** [axodotdev/cargo-dist#200]
I would expect the `.zip` to say `zip file` or similar, here.

![image](https://user-images.githubusercontent.com/17535/224153723-de64c8f8-2932-4af5-98e6-f00e11196d6a.png)

**Comment by Gankra** [comment]
Yeah internally cargo-dist considers tarballs and zips to be "the same thing", and tarball felt like the most familiar term for end users. This table is a mess and mostly just exists as a proof of concept, and should be completely reworked (#70). I didn't worry too hard about it because this oranda is the Good Version of this stuff, but I wanted to have something for people Not Using Oranda (which especially now is "everyone").

**Comment by Gankra** [comment]
This format changed a long time ago so this isn't a thing.
