### ISSUE TITLE
Use parse_changelog::Release::title_no_link

### ISSUE THREAD

**Issue by IgnisDa** [axodotdev/cargo-dist#262]
Extending https://github.com/taiki-e/parse-changelog/issues/32.

For example, https://github.com/github-changelog-generator/github-changelog-generator generates headings in the following format:

```markdown
## [v1.0.0-beta.55](https://github.com/ignisda/ryot/tree/v1.0.0-beta.55) (2023-06-05)

[Full Changelog](https://github.com/ignisda/ryot/compare/v1.0.0-beta.54...v1.0.0-beta.55)

**Closed issues:**

- Error: Failed to read source file. [\#116](https://github.com/IgnisDa/ryot/issues/116)
```

But cargo-dist generates the announcement title as follows:
![image](https://github.com/axodotdev/cargo-dist/assets/60938164/14a5915e-d8ef-48b5-bd05-727cdc3b1f75)

I want it to be like `v1.0.0-beta.55 (2023-06-05)`.

**Comment by IgnisDa** [comment]
It can be configurable via the cargo dist section in `Cargo.toml`, maybe via a key called `header-format`. Would you accept a PR for the  same?

**Comment by IgnisDa** [comment]
@axodotdev Any updates on this?

**Comment by Gankra** [comment]
Ok so just checking I understand this:

* The tool you are using generates a changelog file with a link hardcoded into the text
* We then forward that along verbatim as the "title" of the announcement, when the link should be stripped out
* Release::title_no_link does this stripping exactly

If this is the case then I don't think we need config, we just need to unconditionally use that method, since I don't think anyone would want that link to be forwarded when using cargo-dist..?

**Comment by IgnisDa** [comment]
Yep this is correct. I don't really care for the link at all.

**Comment by IgnisDa** [comment]
Hey @Gankra any updates?

**Comment by Gankra** [comment]
omg so sorry, I forgot to put this in a milestone so it didn't get put in someone's todo-list.

The relevant code is being migrated to axoproject, so I've filed this "upstream" https://github.com/axodotdev/axoproject/issues/36 and scheduled it for the next release (cutting 0.2.0 today so not making the cut).
