### ISSUE TITLE
failing while uploading artifacts --> requires at least 2 arg(s), only received 1

### ISSUE THREAD

**Issue by Masber** [axodotdev/cargo-dist#266]
Hi,
My artifact release/upload to github releases is failing because I am missing an argument but i don't know which argument am I missing
Any idea?
```
Run # Actually do builds and make zips and whatnot
  # Actually do builds and make zips and whatnot
  cargo dist build --tag=v0.6.3 --output-format=json --artifacts=global > dist-manifest.json
  echo "dist ran successfully"
  cat dist-manifest.json
  
  # Parse out what we just built and upload it to the Github Release™
  jq --raw-output ".artifacts[]?.path | select( . != null )" dist-manifest.json > uploads.txt
  echo "uploading..."
  cat uploads.txt
  gh release upload v0.6.3 $(cat uploads.txt)
  echo "uploaded!"
  shell: /usr/bin/bash -e {0}
  env:
    GH_TOKEN: ***
analyzing workspace:
  manta
    [bin] manta

dist ran successfully
{
  "dist_version": "0.1.0-prerelease.2",
  "announcement_tag": "v0.6.3",
  "announcement_is_prerelease": false,
  "announcement_title": "v0.6.3",
  "announcement_github_body": "",
  "releases": [
    {
      "app_name": "manta",
      "app_version": "0.6.3"
    }
  ]
}
uploading...
requires at least 2 arg(s), only received 1
Error: Process completed with exit code 1.
```

**Comment by Gankra** [comment]
I believe the error in question is Github's `gh` cli complaining that we are running `gh release upload v0.6.3` without any actual file arguments. This happens when a cargo-dist task runs and then finds no files it actually needs to upload. In this case it appears to be the `global` task, which is responsible for uploading installers.

When generating the CI script cargo-dist shouldn't generate the `global` task if that would happen. My best guess is that you made some edits to your config and didn't regenerate the CI (something that's non-obvious and cargo-dist should try to improve on, #178).

If you run `cargo dist generate-ci`, does the global task get removed from the github ci script? (`cargo dist init` also runs `generate-ci` for you, and does some more integrity checks). 

If that doesn't work then probably there's a bug in the ci generator.

**Comment by Masber** [comment]
yes, running `cargo dist init` again fixed the issue, thank you
