### ISSUE TITLE
Add support binaries with required features

### ISSUE THREAD

**Issue by Tiwalun** [axodotdev/cargo-dist#274]
In https://github.com/probe-rs/probe-rs/, we have a couple of binaries which only get built when a feature is enabled. Right now, cargo-dist tries to release these binaries even though they can't be built without the required feature.

It would be great if cargo-dist could enable the required features automatically, or at least have a setting for it in the configuration.

Might be a duplicate of #22

**Comment by Tiwalun** [comment]
Would you accept a PR implementing support for this? 

My plan for implementing it would be to keep track of required features for the binaries, and pass that along to the build step, without exposing any additional config settings.

**Comment by Gankra** [comment]
Oh whoops, sorry I need to be more proactive in doing triage -- I think this is definitely something we want! Ideally we could just detect that your build is Like This so no configuration would be required -- how are you expressing it to cargo?

(PRs are welcome of course, but this requires some non-trivial config/ux work)

**Comment by Yatekii** [comment]
So we have a combined lib/bin crate. To not pull all sorts of crates into the lib target, we have a `cli` feature that is required to build the bin target.
We have no way to tell cargo that it is required. Of course we could make it a default feature, but that would mean all the lib users have to use `default-features=false` when they use the library.
So the only way I see is having custom cargo metadata or passing it via CLI.
I was snooping a bit in the code and it seems non-trivial to patch this, since we cannot just pass the features to all crates.

If we find some good solution for this, I am happy to PR.

**Comment by Gankra** [comment]
I think that would make perfect sense with the `precise-builds` config in the 0.1.0 release (coming out tomorrow). If you set a feature on a package we can just force enable precise builds.

**Comment by Yatekii** [comment]
I gave it a jab here: https://github.com/axodotdev/cargo-dist/pull/317 it requires to set `precise-builds` manually atm. Also, I am not sure the code is the cleanest it could be.
Feel free to copy paste/push into the PR however you like :)

**Comment by Gankra** [comment]
Oh lord, sorry ok this feature *is* needed because [required-features](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-required-features-field) doesn't do what I thought.

> The required-features field specifies which [features](https://doc.rust-lang.org/cargo/reference/features.html) the target needs in order to be built. If any of the required features are not enabled, the target will be skipped.

So this is just telling cargo that the build can be skipped without those features. Unfortunately there was an error in prerelease.1, so I'll cut prerelease.2 with a fix in about an hour.

**Comment by Gankra** [comment]
v0.2.0-prerelease.2 should work and has the desired functionality 

https://github.com/axodotdev/cargo-dist/releases/tag/v0.2.0-prerelease.2

**Comment by IgnisDa** [comment]
@Gankra I get the error https://github.com/IgnisDa/ryot/actions/runs/5941550457/job/16114985815#step:7:1148 with v0.0.7 and v0.1.0 (which I tried locally). What can I do to fix it? Thanks.
