### ISSUE TITLE
Add `super-linter`?

### ISSUE THREAD

**Issue by smallstepman** [axodotdev/cargo-dist#301]
Would you be open to adding https://github.com/super-linter/super-linter to this project?
Here is the output from running it on tip of this repo: https://github.com/smallstepman/cargo-dist/actions/runs/5763809454/job/15626410522#step:4:57

**Comment by Gankra** [comment]
Wow that's a lot of linters. Seems like we'd need to spend quite a while tuning them to work right.

* Whatever process it's using for picking out files isn't properly ignoring the .j2 files (so e.g. the shellchecker is running on installer.sh.j2 when it shouldn't be, we run shellcheck in ci post-expansion of the template, so i'm pretty confident it works).

* textlint is the kind of pedantic I don't like in CI (spellcheck on technical documentation is Hell)

* markdownlint has some good complains but needs some callibration (the long lines are intentional, idk about the various random style guides)

* no idea what jscpd is or what it's trying to tell me, it seems like gibberish

* seems to be recommending unconventional quoting of `run` in github ci ymls (minor, could take or leave it)

I'm not opposed to this but this is a lot to take in.

**Comment by smallstepman** [comment]
yea I agree there is a lot of stuff there :D 

---

> no idea what jscpd is or what it's trying to tell me, it seems like gibberish

[`jscpd`](https://github.com/kucherenko/jscpd) tells you there is duplicated code, from their readme:
> Copy/paste detector for programming source code, supports 150+ formats. Copy/paste is a common technical debt on a lot of projects. The jscpd gives the ability to find duplicated blocks implemented on more than 150 programming languages and digital formats of documents. The jscpd tool implements [Rabin-Karp](https://en.wikipedia.org/wiki/Rabin%E2%80%93Karp_algorithm) algorithm for searching duplications. 

---

> seems to be recommending unconventional quoting of run in github ci ymls (minor, could take or leave it)

The error is hard to read and doesn't point to the right place, but there are two different reasons:
1.  it wants to see this `cargo publish -p cargo-dist-schema --token ${CRATES_TOKEN}` changed into this ` cargo publish -p cargo-dist-schema --token "${CRATES_TOKEN}"`
2. `.github/workflows/release.yml:119:9: shellcheck reported issue in this script: SC2046:warning:10:42: Quote this to prevent word splitting [shellcheck]` it want to change this `          gh release upload ${{ github.ref_name }} $(cat uploads.txt)` to this `          gh release upload ${{ github.ref_name }} "$(cat uploads.txt)"` (I don't have windows so I cannot verify if it still works there)


---

> Whatever process it's using for picking out files isn't properly ignoring the .j2 files (so e.g. the shellchecker is running on installer.sh.j2 when it shouldn't be, we run shellcheck in ci post-expansion of the template, so i'm pretty confident it works).

> textlint is the kind of pedantic I don't like in CI (spellcheck on technical documentation is Hell)


I excluded `installer.sh.j2` from listing, disabled `textlint` and let the CI run again: https://github.com/smallstepman/cargo-dist/actions/runs/5765577745/job/15631804140

--- 


> markdownlint has some good complains but needs some callibration (the long lines are intentional, idk about the various random style guides)

This will require more effort, but I can fix everything listed there (and leave long lines untouched and ignored by linter) - let me know

**Comment by Gankra** [comment]
Whoops, sorry I totally let this slip -- could you open a PR with what you have so far so it's actively in the work queue?

**Comment by smallstepman** [comment]
sure! I won't have much time this week to finish this but I'll try to pick it up next week
