### ISSUE TITLE
Generated PowerShell installer prints confusing error

### ISSUE THREAD

**Issue by ticky** [axodotdev/cargo-dist#484]
Hi there! Love cargo-dist!

I primarily develop on macOS and Linux but for the first time I packaged something with the PowerShell option enabled, and tested it out on a little Windows machine I have. I received the following message:

![Screenshot 2023-10-16 195053](https://github.com/axodotdev/cargo-dist/assets/282113/c88ee378-de73-4870-80bb-f537a80c30f0)

(this screenshot was taken from a freshly launched Windows Sandbox as the Windows machines I have access to now all have their ExecutionPolicy set appropriately)

Having run into ExecutionPolicy stuff before, I knew what to do, but this isn't a particularly helpful error message, and doesn't really make it clear to someone who's not knowledgeable about PowerShell what the remediation steps are. It also feels a little unexpected that it's reporting it can't "run" my app, despite this being an installer for it.

I notice, reading through the code of the generated installer, that it _is_ attempting to provide additional context, but this is never displayed, at least on a the Windows 10 installations I've tested:

```powershell
  # show notification to change execution policy:
  $allowedExecutionPolicy = @('Unrestricted', 'RemoteSigned', 'ByPass')
  If ((Get-ExecutionPolicy).ToString() -notin $allowedExecutionPolicy) {
    Write-Error "PowerShell requires an execution policy in [$($allowedExecutionPolicy -join ", ")] to run $app_name."
    Write-Error "For example, to set the execution policy to 'RemoteSigned' please run :"
    Write-Error "'Set-ExecutionPolicy RemoteSigned -scope CurrentUser'"
    break
  }
```

I'm no PowerShell dev, so I don't really know what the solution is here - it does seem from a glance at Microsoft's docs like `Write-Error` is not supposed to immediately exit, but the first line is all I see across multiple machines, and now in Windows Sandbox, which shouldn't be affected by any of my system's configuration changes. Perhaps concatenating the messages into one message with embedded newlines?

In any case, thanks for the great tool! Keep it up :)

**Comment by Gankra** [comment]
> Having run into ExecutionPolicy stuff before

Well that makes one of us! I started reading this issue *very* confused because `Initialize-Environment` is some logic I inherited [from an ancestor of this project and I've never had to modify it before](https://github.com/apollographql/rover/commit/d2cee554c70ab91547dbc1ec208a0a790b2b524d). Genuinely forgot it existed.

And yeah the way powershell streams work is really brain-hurty. Now that I understand them better and have a reason to reread this code, it definitely isn't doing what we want. Basically the statement that Write-Error is non-terminating is kinda a lie -- it's not *required* to terminate (unlike throw), and it won't in a default environment. However the parent function sets `$ErrorActionPreference = 'stop'` which basically turns non-terminating errors into terminating ones. Oops!

This code should just be rewritten to use throws with one unified message, as you say.
