### ISSUE TITLE
sysdeps on aarch64-apple-darwin

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/cargo-dist#498]
currently, cargo-dist targets aarch64-apple-darwin as a cross target, which means that projects that require native sysdeps are particularly challenging. this is a tracking issue for folks who have this issue, and thoughts about how to approach it.

**Comment by mistydemeo** [comment]
We're slightly constrained here because we don't have access to native M1 runners. GitHub [recently launched](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) M1 runners, but only as an "xlarge" runner. This is one of their categories of runners that's exclusively available as a paid option; thus far, we've tried to ensure that all of our CI options can run on the free runners.

I do realize, though, that we're a bit more constrained than we need to be because I have us unconditionally `brew bundle exec`ing on arm64. That's failing not just because libraries are compiled for Intel, but because it's injecting build environment variables that are inappropriate for cross-compiling to arm64. I'm going to improve this case before ship. I have two ideas:

* aarch64-apple-darwin builds still `brew bundle install` deps, but no longer do `brew bundle exec`. As a result, it doesn't get any of the build environment modification that Intel does, but commandline tools that are installed onto the `PATH` will work.
* Replace `brew bundle exec` with tooling that picks and chooses which parts of `brew bundle exec`'s environment we want, and then use only those variables/values within our builds. In this case we can actually inherit the same behaviour on Intel. This still won't let aarch64-apple-darwin builds get access to C libraries, but otherwise keeps a bunch of extra niceties we get from `brew bundle exec`.

**Comment by mistydemeo** [comment]
After shipping #499/#504, I've improved the case in GitHub CI. We now no longer always tank builds, and builds using non-library dependencies will work fine. Builds that actually require C libraries will still fail, however, and that won't be fixable until we have a CI option with ARM64 runners.

**Comment by weiznich** [comment]
I believe that this is still broken with the `cargo dist` 0.4 release from today. If you specify dependencies via `[package.metadata.dist.dependencies.homebrew]` key, cargo dist currently seem to install always the x86_64 version of the libraries. That leads to linker errors, complaining about incompatible library versions. [See here for an example CI run where this error occurs) 

I currently workaround that limitation by manually installing the right dependencies again for diesel. See [here](https://github.com/diesel-rs/diesel/pull/3833/commits/1baef7d845eb51e75d8d4d39ac9426b04fd22716#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R106-R117) for the relevant step in the CI setup.

**Comment by mistydemeo** [comment]
> I believe that this is still broken with the cargo dist 0.4 release from today.

Specifically, we scoped this to a method that allows CLI tools to be installed; you're right that libs are still broken.

> I currently workaround that limitation by manually installing the right dependencies again for diesel. See [here](https://github.com/diesel-rs/diesel/pull/3833/commits/1baef7d845eb51e75d8d4d39ac9426b04fd22716#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R106-R117) for the relevant step in the CI setup.

Very interesting! It's a clever hack. Does that handle recursive dependencies correctly? I'm worried you'd have to walk the tree to get those installed with the right bottle tag.

This would be harder for us to integrate since we make use of `brew bundle` for environment stuff, and it's not exposing the flags you're using there. But we might need to look into this if we continue to not have an option to do this natively.

**Comment by weiznich** [comment]
> Specifically, we scoped this to a method that allows CLI tools to be installed; you're right that libs are still broken.

It would be great to point that out in the documentation.

>  Does that handle recursive dependencies correctly? I'm worried you'd have to walk the tree to get those installed with the right bottle tag.

I'm not sure if it does recursively resolve dependencies. I can only say that this is sufficient to satisfy the compiler to link against these libraries.

**Comment by mistydemeo** [comment]
> It would be great to point that out in the documentation.

The documentation actually claims it doesn't work at all right now: https://opensource.axo.dev/cargo-dist/book/ci/github.html#limitations I didn't update that to indicate that you can install CLI tools.

**Comment by mistydemeo** [comment]
I'll reopen this until we clarify the current state of things in the docs.
