### ISSUE TITLE
Linuxbrew Support

### ISSUE THREAD

**Issue by dsully** [axodotdev/cargo-dist#501]
Hi - would a PR be accepted to add Linuxbrew support?

Thanks!

**Comment by Gankra** [comment]
We weren't going to add linuxbrew ourselves, but were aware of it when we made the homebrew support, and left some logical room for it one day. If you're willing to do the work to implement it, we'd be very happy to accept it!

Did you have any requirements/plans for what you want to work?

I believe the main concern for us is that if a user opts into homebrew support, we probably shouldn't *default* to also doing linuxbrew, because that may surprise them and their linux users. One of the ways we had planned that was that when specifying a [dependencies.homebrew], without specifying `target = ...`, we would only ever apply them to macos targets, and you could "opt in" to linuxbrew targets by manually enumerating the platforms you care about (this would also specifically let you say "linuxbrew only, not macos homebrew").

**Comment by mistydemeo** [comment]
I'd love to learn more about your usecase here! I'm curious about the circumstances in which you'd prefer Linuxbrew over apt (or any other Linux package manager).

I'd be happy to review a PR, and to work with you to scope the work or provide any guidance you nee din the PR process.

**Comment by dsully** [comment]
Homebrew packages are almost always more recent than even Ubuntu (which I use). Using Linuxbrew and Homebrew allows for a nearly combined manifest of packages:

https://github.com/dsully/dotfiles/blob/main/home/dot_config/Brewfile.tmpl

For my own tools that I release to my tap, I'd like to do the same:

https://github.com/dsully/homebrew-tap

@Gankra I'm curious how adding a Linuxbrew target would surprise a user? If they aren't using Linuxbrew, and they don't specify a package, it would be no-op. Unless I'm missing something?

I'd think the logical behavior would be to automatically add Linux artifacts to the tap if they exist - and also be multi-architecture aware, specifically `x86_64` and `arm64 / aarch64`

**Comment by mistydemeo** [comment]
> If they aren't using Linuxbrew, and they don't specify a package, it would be no-op. Unless I'm missing something?

Linuxbrew is preinstalled on the GitHub Ubuntu runners, so builds running there automatically have it. I do think many users who intend to use apt packages would be surprised to see Linuxbrew packages installed too!

> For my own tools that I release to my tap, I'd like to do the same:

I see, so it sounds like you're most interested in the publishing story rather than using Linuxbrew to install packages before the build?

**Comment by dsully** [comment]
> Linuxbrew is preinstalled on the GitHub Ubuntu runners, so builds running there automatically have it. I do think many users who intend to use apt packages would be surprised to see Linuxbrew packages installed too!

I wasn't aware of that. It would still require someone to call `brew install <package>` instead of `apt-get install <package>` though?

> I see, so it sounds like you're most interested in the publishing story rather than using Linuxbrew to install packages before the build?

Yes! Sorry if I didn't make that clear. 100% on what is generated for the Formula `.rb` file.

**Comment by mistydemeo** [comment]
> I wasn't aware of that. It would still require someone to call brew install <package> instead of apt-get install <package> though?

I think where we're talking at cross-purposes here is that we just (in 0.4.0) shipped a feature that lets users install dependencies *from* a package manager as a part of the build process. I've been so focused on that I assumed that's what your question was about. 😅 That aspect of Linuxbrew support, which is what @Gankra and I were talking about, has a few more complex questions to work through... but adding binaries to the Homebrew `.rb` formula file is a lot more straightforward.
