### ISSUE TITLE
sed error in install script

### ISSUE THREAD

**Issue by ethankhall** [axodotdev/cargo-dist#773]
I'm using `cargo-dist` in a project, and was testing out the install script and saw an error message.

```
curl --proto '=https' --tlsv1.2 -LsSf https://github.com/ethankhall/scope/releases/download/v2024.2.4/dev-scope-installer.sh | sh
sed: 1: "s,"CARGO_DIST_BINS","sc ...": bad flag in substitute command: '"'
```

The install looks to have worked, but I would expect to not see this error message.

## System Details

```
❯ echo $SHELL
/bin/zsh
❯ zsh --version
zsh 5.9 (x86_64-apple-darwin23.0)
❯ sh --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by Gankra** [comment]
Ah shoot

```
    RECEIPT="$(echo "$RECEIPT" | sed s,'"CARGO_DIST_BINS"',"$_bins_js_array",)"
```

This sed uses `,` instead of `/` to avoid the obvious problems of path separators, but then runs into the fact that we represent a list of binaries as `a,b`... which makes using `,` as a delimiter freak out.

This only affects "install receipts" which is a ground-work feature for future updater work. So your installer works fine but gets that ugly message. Definitely need to fix this and cut a quick release -- thanks for reporting!!

**Comment by Gankra** [comment]
good news, we have tests that cover this situation

https://github.com/axodotdev/cargo-dist/blob/2241187b843a91af4ec1e7140237a465732f5763/cargo-dist/tests/snapshots/akaikatana_basic.snap#L156

bad news, they don't check that the install receipt got installed (time to add that)
