### ISSUE TITLE
Bug Report: Could not find directory of OpenSSL installation

### ISSUE THREAD

**Issue by d1onys1us** [axodotdev/cargo-dist#786]
I am facing this build issue here: https://github.com/d1onys1us/stn/actions/runs/7852370373/job/21430665311#step:7:508

For linux-musl build. Please let me know if I shoulud provide more details.

**Comment by mistydemeo** [comment]
The issue comes from linking against OpenSSL when building the `openssl-sys` crate. Because the host OS the build is running on uses glibc, the OpenSSL you have available to link against uses glibc instead of musl; it's incompatible with a musl build. You'll want to either avoid linking to OpenSSL, or use custom runners to build on a musl-based host OS.

**Comment by ashleygwilliams** [comment]
hey @d1onys1us - @mistydemeo is right about this. i took a look at your cargo.toml and while you are using rustls for all the tokio/hyper deps, it looks like the ethers crate depends on nativetls *and* doesn't seem to have a rustls feature yet- did find this issue here which you can upvote/comment perhaps: https://github.com/gakonst/ethers-rs/issues/781
