### ISSUE TITLE
Build binaries with `cargo auditable`

### ISSUE THREAD

**Issue by Aloso** [axodotdev/cargo-dist#81]
This makes sure that all dependencies and their versions are embedded in the binary in a machine-readable format, and can be obtained with `cargo audit bin`. This allows auditing binaries for vulnerabilities that weren't yet known when the binaries were built.

**Comment by Shnatsel** [comment]
Author of [`cargo auditable`](https://github.com/rust-secure-code/cargo-auditable) here 👋 

I'd love to see this integration and I'm happy to support it on my end!

There's precedent for transparently enabling this in Linux distros: Void Linux builds all their Cargo packages with `cargo auditable`, and Nix is canarying it on a few popular packages before rolling it out to the entire archive. So it's been tested pretty widely and is known to work with a wide variety of packages, and not break even in exotic configurations.

And it's not just [`cargo audit`](https://crates.io/crates/cargo-audit) that consumes this data, [Syft](https://github.com/anchore/syft) and [Trivy](https://github.com/aquasecurity/trivy) can read it as well. That's how Microsoft uses it.

The only caveat I can think of is unsupported platforms - `cargo auditable` will refuse to build WASM because it doesn't know how to make it auditable. But I can just add an environment variable you can set to ignore unsupported platforms and that should ensure there's no breakage.

**Comment by Gankra** [comment]
(will re-evaluate this when core stuff is more settled, thanks for the info!)

**Comment by simonsan** [comment]
Hey, just wanted to chime in to state, that I'm really looking forward to this! (:

**Comment by duckinator** [comment]
This was implemented in #1528. To have dist use `cargo auditable build` instead of `cargo build`, you can add this to the `[dist]` section of `dist-workspace.toml`:

```
cargo-auditable = true
```

**Comment by Shnatsel** [comment]
That's great news!

Is this capability documented in the Dist Book?

**Comment by duckinator** [comment]
Forgot an important part: once you make that config change, you can run `dist generate` and your workflow will be modified to install `cargo-auditable` installed for you.

Locally, you still need to install cargo-auditable manually. #1527 has been opened to handle that.

**Comment by mistydemeo** [comment]
We also haven't yet cut a release with this feature - but we likely will fairly soon!

**Comment by duckinator** [comment]
Documentation for the `cargo-auditable` feature has been merged. :slightly_smiling_face:
