### ISSUE TITLE
there isn't a package for x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by ahaoboy** [axodotdev/cargo-dist#932]
There is no x86_64-pc-windows-gnu option.
```
cargo-dist 0.13.1


? what platforms do you want to build for?
    (select with arrow keys and space, submit with enter) ›
  [ ] Apple Silicon macOS (aarch64-apple-darwin)
  [ ] Intel macOS (x86_64-apple-darwin)
  [x] x64 Linux (x86_64-unknown-linux-gnu)
  [x] x64 MUSL Linux (x86_64-unknown-linux-musl)
  [x] x64 Windows (x86_64-pc-windows-msvc)

```

Release x86_64-pc-windows-msvc version, then local rust set default x86_64-pc-windows-gnu toolchain, when execute install script will report error.

**Comment by Gankra** [comment]
We don't have any immediate plans to support building for mingw, but with #984 we now properly regard windows-msvc as a valid fallback for windows-gnu.

**Comment by ahaoboy** [comment]
> we now properly regard windows-msvc as a valid fallback for windows-gnu.
Make sense, both formats work fine for Win.

**Comment by Ayush1325** [comment]
> We don't have any immediate plans to support building for mingw, but with #984 we now properly regard windows-msvc as a valid fallback for windows-gnu.

Hi, so I was wondering what you mean by supporting MinGW? I tried adding `x86_64-pc-windows-gnu` to known targets (https://github.com/Ayush1325/cargo-dist/tree/windows-cross) and it seems like it compiles and packages the executable just fine. So do you mean you do not plan on supporting MinGW for msi installers? Because I think just the executable distribution is also extremely useful.
